language: java
jdk:
  - openjdk8
 
#master 브랜치에 push되었을 때만 수행
branches:
 only:
  - master

#Travis CI 서버의 Home path  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


#master 브랜치에 push되었을 때 수행하는 명령  
script: "./gradlew clean build"

#CI 실행 결과를 받을 메일 주소
#추후 이메일외에 Slack또한 추가 예정
notifications:
  email:
    recipients:
      - sencom1028@gmail.com